### ISSUE TITLE
Improve checkov output in pre-commit.

### ISSUE THREAD

**Issue by pimielowski** [PaloAltoNetworks/terraform-google-vmseries-modules#135]
### Is your feature request related to a problem?

Right now we don't specify which test we want to check, and the result of that is whole errors which checkov makes are skipped because they touch something we don't need or wont to check.

### Describe the solution you'd like

We need to clarify which test we want to do with check and properly configure it.

**Comment by horiagunica** [comment]
## Pre-commit YAML modification

- Modified the checkov hook to exclude certain checks
- Some of them still need modifications


| Checkov ID      | Description | Status     |
| :---            |    :----:   |      :---: |
| CKV_GCP_26      | Ensure GCP VPC flow logs for the subnet is set to On | Excluded
| CKV_GCP_32      | Ensure ‘Block Project-wide SSH keys’ is enabled for VM instances | Excluded
| CKV_GCP_35      | Ensure ‘Enable connecting to serial ports’ is not enabled for VM Instance | Excluded
| CKV_GCP_36      | Ensure that IP forwarding is not enabled on Instances | Excluded
| CKV_GCP_37      | Ensure VM disks for critical VMs are encrypted with Customer Supplied Encryption Keys (CSEK) | Excluded
| CKV_GCP_38      | Ensure VM disks for critical VMs are encrypted with Customer Supplied Encryption Keys (CSEK) | Excluded
| CKV_GCP_40      | Ensure that Compute instances do not have public IP addresses | Excluded
| CKV_GCP_62      | Bucket should log access | Excluded
| CKV_GCP_74      | Ensure that private_ip_google_access is enabled for Subnet | Excluded
| CKV_GCP_76      | Ensure that Private google access is enabled for IPV6 | Excluded
| CKV_GCP_83      | Ensure PubSub Topics are encrypted with Customer Supplied Encryption Keys (CSEK) | Excluded
| CKV_GCP_106     | Ensure Google compute firewall ingress does not allow unrestricted http port 80 access | Excluded

- The following should be confirmed before excluding them :

| Checkov ID      | Description | Status     |
| :---            |    :----:   |      :---: |
| CKV_GCP_39      | Ensure Compute instances are launched with Shielded VM enabled | To Be Confirmed for Exclusion
| CKV_GCP_78      | Ensure Cloud storage has versioning enabled | To Be Confirmed for Exclusion
| CKV_GCP_30      | Ensure that instances are not configured to use the default service account | To Be Confirmed for Exclusion

- Also excluded some configs from the "examples" folder since they generate no errors - here is code snippet on how to exclude based on resource by resource terraform configuration :

```go
resource "google_compute_instance" "spoke1_vm" {
  #checkov:skip=CKV_GCP_30:Examples - can use default service account - https://docs.bridgecrew.io/docs/bc_gcp_iam_1
  #checkov:skip=CKV_GCP_39:Examples - can use non-shielded VM - https://docs.bridgecrew.io/docs/bc_gcp_general_y
  count                     = 2
  name                      = "${local.prefix}spoke1-vm${count.index + 1}"
  machine_type              = var.spoke_vm_type
  zone                      = data.google_compute_zones.main.names[0]
  can_ip_forward            = false
  allow_stopping_for_update = true
}
```

Syntax is :

```bash
#checkov:skip=<CHECK_ID>:<Exclusion comment>
```
